import Head from "next/head";
import Link from "next/link";
import { useInView } from 'react-intersection-observer';
import { useState, useEffect } from "react";
function Home() {
  const [ref, inView] = useInView({
    triggerOnce: true, // trigger animation only once
    threshold: 0.5, // intersection ratio for triggering the animation
  });
  const [scrollIndex, setScrollIndex] = useState(0);

  useEffect(() => {
    const handleInterval = () => {
      setScrollIndex(prevIndex => (prevIndex + 1) % 3);
    };

    let intervalId = null;
    const handleResize = () => {
      const isMobile = window.innerWidth <= 888;
      if (isMobile) {
        intervalId = setInterval(handleInterval, 5000);
      } else {
        clearInterval(intervalId);
      }
    };

    handleResize(); // Initial check

    window.addEventListener('resize', handleResize);

    return () => {
      clearInterval(intervalId);
      window.removeEventListener('resize', handleResize);
    };
  }, []);

  const [currentSlide, setCurrentSlide] = useState(0);
  const slides = [
    "/imgs/Slide 1.jpg",
    "/imgs/slide 2.jpg",
    "/imgs/slide 3.jpg",
    "/imgs/slide 4.jpg"
  ];

  useEffect(() => {
    const interval = setInterval(() => {
      setCurrentSlide((prevSlide) => (prevSlide === slides.length - 1 ? 0 : prevSlide + 1));
    }, 3000);

    return () => clearInterval(interval);
  }, []);

  const goToSlide = (slideIndex) => {
    setCurrentSlide(slideIndex);
  };

  const nextSlide = () => {
    setCurrentSlide((prevSlide) => (prevSlide === slides.length - 1 ? 0 : prevSlide + 1));
  };

  const prevSlide = () => {
    setCurrentSlide((prevSlide) => (prevSlide === 0 ? slides.length - 1 : prevSlide - 1));
  };


  return (
    <>
      <Head>
        <title>North Beta - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="/imgs/logo.png" type="image/x-icon" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />
      </Head>
      <div className="head-banner">
        <div className="page-info">
          <h1 className="heading-main">SCALING SUCCESS AS A COMMUNITY</h1>
          <h4>JOIN A GLOBAL NETWORK OF GENERATIVE AI LEADERS</h4>
          <Link href="/portfolio" className="subscribe-btn main-btn" >Our portfolio</Link>
        </div>
      </div>
      <section className="second-section">
        <div className="bestthings slideleft" >
          <h1 className="main-heading">
            POSITIONING
          </h1>
          <h2 className="heading main-case-desc">FOREFRONT GENERATIVE ARTIFICIAL INTELLIGENCE COMMUNITY</h2>
        </div>
        <div className="bestthings right-things slideright">
          <h1 className="main-heading">
            APPROACH
          </h1>
          <h2 className="heading main-case-desc">COMMUNITY · COMPUTING POWER · INVESTMENT BANKING · INVESTMENT</h2>
        </div>
        <div className="bestthings slideleft">
          <h1 className="main-heading">
            MISSION
          </h1>
          <h2 className="heading main-case-desc">UNITING GREAT MIND TO BUILD A BETTER TOMORROW WITH AI</h2>
        </div>
      </section>
      <section className="invest">
        <div className="carousel">
          <div className="slides-container" style={{ transform: `translateX(-${currentSlide * 100}%)` }}>
            {slides.map((slide, index) => (
              <img
                key={index}
                src={slide}
                alt={`Slide ${index + 1}`}
                className="slide"
              />
            ))}
          </div>
          <button className="prev" onClick={prevSlide}>
            <i class="fa-solid fa-angle-left"></i>
          </button>
          <button className="next" onClick={nextSlide}>
            <i class="fa-solid fa-angle-right"></i>
          </button>
        </div>
        <div className="invest-container">

          <div className="heading">
            <h1>WHY INVEST IN AI?</h1>
          </div>
          <p className="description">Our vision is that Generative Artificial Intelligence will be the key driver of the fourth industrial revolution, in synergy with other technologies such as semiconductors, the internet of things, cloud computing, big data, blockchain, and more. This will result in a radical transformation of productivity and value creation.</p>
          <div className="whyinvest-container">


            <div className="middle-border">

            </div>
            <div className="main-invest-conts first-invest">
              <div className="main-invest right-invest-border">
                <div className="icon">
                  <i class="fa-solid fa-globe icons"></i>
                </div>
                <h3 className="heading-invest">
                  EVOLUTION & ADOPTION
                </h3>
                <p className="desc-invest">No other technology has ever accelerated growth and adoption like GEN AI.</p>
              </div>
              <div className="main-invest left-invest-border">
                <div className="icon">
                  <i class="fa-solid fa-address-book icons"></i>
                </div>
                <h3 className="heading-invest">
                  EXPONENTIAL USER GROWTH
                </h3>
                <p className="desc-invest">ChatGPT grew to 100 Million users in just 2 months, the fastest ever on record.</p>
              </div>
            </div>
            <div className="main-invest-conts second-invest">
              <div className="main-invest right-invest-border">
                <div className="icon">
                  <i class="fa-solid fa-network-wired icons"></i>
                </div>
                <h3 className="heading-invest">
                  Artificial General Intelligence
                </h3>
                <p className="desc-invest">The standard of achieving AGI is still uncharted but the emergence of GEN AI will accelerate the process.</p>
              </div>
              <div className="main-invest left-invest-border">
                <div className="icon">
                  <i className="fa-solid fa-bullseye icons"></i>
                </div>
                <h3 className="heading-invest">
                  DEEP LEARNING & TRAINING
                </h3>
                <p className="desc-invest">No longer do we spoon feed systems. Now we let the algorithm learn from datasets and correct it’s wrong outputs rather than giving our own unbiased inputs.</p>
              </div>
            </div>
          </div>
        </div>

      </section>

      <section className="approach">
        <h1 className="heading">OUR APPROACH</h1>
        <div className="approach-firstrow">

          <h3 className="desc-approach" style={{ color: "#585858", }}>Join our community of GPU-powered innovators and get comprehensive financial support from our growing team of professionals.</h3>
        </div>
        <div className="approach-main">
          <img src="/imgs/our-approach.png" alt="" />
        </div>

      </section>
      <section className="case-study">
        <h1 className="main-heading">CASE STUDY</h1>
        <h2 className="heading main-case-desc">HOW NORTH BETA LABS HELPS ITS COMMUNITY MEMBERS</h2>
        <div className="runsun-study">
          <img src="/imgs/RUNSUN-LOGO-WHITE.png" alt="" />
          <p className="company-desc font-28">Leading GPU cloud provider seeks to be the Coreweave of Asia.</p>
        </div>
        <div className="studies">
          <p className="study company-desc"><b className="bold-study study">Strategic Incubation:</b> North Beta Labs incubated RunSun, facilitating its partnership with Nvidia to become an esteemed Nvidia Cloud Partner. <br /> <br />
            <b className="bold-study study">Financial Support: </b>Invested nearly $100 million in RunSun, positioning itself as the second-largest share- holder and aiding in additional capital raising through debt and prospective equity financing. <br /> <br />

            <b className="bold-study study" >Market Expansion and Resources: </b> Actively connects RunSun with potential customers and is co-creating an on-demand cloud service, simplifying access to computing power for community members.</p>
        </div>
      </section>
      <section className="demand">
        <img src="/imgs/Diagram.png" width="1081px" alt="" />
      </section>
      <section className="core-management">
        <h1 className="heading">CORE MANAGEMENT</h1>
        <div className="management-container">
          <div className="people-container" style={{ transform: `translateX(-${scrollIndex * 100}%)` }}>

            <div className="management-people reverse">
              <div className="one-side">
                <div className="desc-cont">
                  <p className="people-desc"><b className="bold lists-heading">A digitalization pioneer, inspiring industries with visionary ideas and influential leadership. </b><br /></p>
                  <ul className="people-desc list">
                    <li className="lists">Peking University - Masters in Financial Information Engineering</li>
                    <li className="lists">HKU Global CEO Program 2023</li>
                    <li className="lists">Stanford GSB Executive Program 2024</li>
                    <li className="lists">Co-founded North Beta Capital in 2015</li>
                    <li className="lists">2017 Forbes China 30 Under 30</li>
                    <li className="lists"> VP of The Anhui Chamber of Commerce in Shanghai</li>
                  </ul>
                </div>
                <div className="profile-info-cont">
                  <h3 className="comas"><i class="fa-solid fa-quote-left"></i></h3>
                  <div>
                    <h1 className="name">JONATHAN ZHU</h1>
                    <h2 className="profession">CHAIRMAN</h2>
                  </div>

                </div>
              </div>
              <img src="imgs/Jon.jpg" width="523px" alt="" className="people-img top" />
            </div>
            <div className="management-people not-reverse">
              <img src="imgs/SHANDONG.jpg" width="523px" alt="" className="people-img" />
              <div className="one-side">
                <div className="desc-cont">
                  <p className="people-desc"><b className="bold lists-heading">An experienced digitalization expert, serving as a steadfast 'copilot,' offering reliable support to companies navigating the digital landscape. </b><br /></p>
                  <ul className="people-desc list">
                    <li className="lists">Peking University - Bachelor of Economics</li>
                    <li className="lists">BRI EMBA Tsinghua University</li>
                    <li className="lists">EX-CICC and Goldman Sachs</li>
                    <li className="lists">Co-founded North Beta Capital in 2015</li>
                    <li className="lists">2018 Forbes China 30 Under 30</li>
                  </ul>
                </div>
                <div className="profile-info-cont">
                  <h3 className="comas"><i class="fa-solid fa-quote-left"></i></h3>
                  <div>
                    <h1 className="name">SHAODONG HUANG</h1>
                    <h2 className="profession">CO-FOUNDER </h2>
                  </div>

                </div>
              </div>

            </div>
            <div className="management-people reverse">

              <div className="one-side">
                <div className="desc-cont">
                  <p className="people-desc"><b className="bold lists-heading">An innovative strategist bridging digital theory with practical application, spearheading research-driven digitalization initiatives. </b><br />           </p>
                  <ul className="people-desc list">
                    <li className="lists">Harvard College</li>
                    <li className="lists">BS in Computer Science</li>
                    <li className="lists">Forbes 2023 Top Overseas Returnee</li>
                    <li className="lists">Ex-Microsoft</li>
                    <li className="lists">Ex-Qisheng Technology</li>
                  </ul>
                </div>
                <div className="profile-info-cont">
                  <h3 className="comas"><i class="fa-solid fa-quote-left"></i></h3>
                  <div>
                    <h1 className="name">JASON ZHAO</h1>
                    <h2 className="profession">PARTNER </h2>
                  </div>

                </div>

              </div>
              <img src="imgs/Jason.jpg" width="523px" alt="" className="people-img" />
            </div>

          </div>

        </div>
      </section>

    </>
  );
}
export default Home;